#!/bin/bash

# Environmental variables indicating where Wine installer can be found.
WINE_INSTALLER_PATH="$HOME"/wine-installer
# Different Wine versions are installed to this path by wine-installer.
WINE_INSTALL_PATH="$HOME"/wine-compiles

# Initialize Wine installer functions.
source "$WINE_INSTALLER_PATH"/bash-functions.sh "$WINE_INSTALL_PATH" "$WINE_INSTALLER_PATH"

# Load the newest Wine version on start or system version if one exists.
winever "`winever | tail -n 1`"
