#!/bin/bash

# Environmental variables indicating where Wine installer can be found
WINE_INSTALL_PATH="$HOME"/wine-compiles
WINE_INSTALLER_PATH="$HOME"/wine-installer

# Initialize Wine installer functions
source "$WINE_INSTALLER_PATH"/bash-functions.sh "$WINE_INSTALL_PATH" "$WINE_INSTALLER_PATH"

# Load the newest Wine version on start
winever "`winever | tail -n 1`"
